# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa8576ddbf308f1739eb5d101aef0a8ede111ce06d8be04f6d07ef4d32ec328f4a25a676706400d6dfa6f898bdbbd0f2d8e27939e2d082c1b0425f027dfe6b8

test:
  secret_key_base: 115a301a4e28689feeba956314f81b15aa2a6c0cd941771e6f8e0f6e2807225c2a0348b9c47f17b1f8192bb3c35913c88734b86b906c1d50a0acc2241332f13e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
